import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Main from '@/components/main';
import {getServerSession} from 'next-auth';
import authConfig from '@/configs/auth';
import Provider from '@/provider/client-provider';
import DbProvider from '@/provider/db-provider';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({children}: {children: React.ReactNode}) => {
  const session = await getServerSession(authConfig);
  return (
    <html lang='en'>
      <DbProvider>
        <Provider session={session}>
          <body className={inter.className}>
            <Header />
            <Main>{children}</Main>
          </body>
        </Provider>
      </DbProvider>
    </html>
  );
};
export default RootLayout;
